//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace remont
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int ID_Applications { get; set; }
        public System.DateTime DateAdd { get; set; }
        public string Device { get; set; }
        public string Problem { get; set; }
        public string Descriotion { get; set; }
        public int User_ID { get; set; }
        public Nullable<int> Status_ID { get; set; }
        public Nullable<int> Executor_ID { get; set; }
    
        public virtual Executor Executor { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
